### ISSUE TITLE
Add PDF handling

### ISSUE THREAD

**Issue by uuuser-name** [Psionica/autocards#7]
Add a way for the users to feed a pdf, allows them to select which pages they want to program to create questions on, and automatically extract, consume, and create questions on these pages.
Useful for textbooks and papers.

see #8 for the same idea, but with web-scraping.

**Comment by thiswillbeyourgithub** [comment]
I did it for you, I intend to add it as a PR in the coming weeks.

**Comment by thiswillbeyourgithub** [comment]
done in the latest revision

**Comment by paulbricman** [comment]
@thiswillbeyourgithub addressed this in #15, but the repo still needs some polishing.
