### ISSUE TITLE
Add web-scraping capabilities

### ISSUE THREAD

**Issue by uuuser-name** [Psionica/autocards#8]
Add a way for the users to give a URL, to get the given URL scraped, and consume, + create questions of, the content.

useful for articles, online textbooks, online non-pdf papers.
see #7 for the same idea but with PDF handling.

**Comment by thiswillbeyourgithub** [comment]
done, in the latest revision

**Comment by paulbricman** [comment]
@thiswillbeyourgithub addressed this in #15, but the repo still needs some polishing.
